models.py
# -*- coding: utf-8 -*-
from app import db
from datetime import datetime
import re
from flask_security import UserMixin, RoleMixin

### Преобразование для ЧПУ ###
def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


### Таблица тегов ###
post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


### Посты ###
class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True)  # ID
    title = db.Column(db.String(140))               # Заголовок
    slug = db.Column(db.String(140), unique=True)   # URL ЧПУ
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now()) # Дата создания

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)


    def __repr__(self):
        return '<Post id: {}, title: {}>'.format(self.id, self.title)


### Тэги ###
class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)    # ID
    name = db.Column(db.String(100))                # Заголовок
    slug = db.Column(db.String(100), unique=True)   # URL ЧПУ

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)


    def __repr__(self):
        return '{}'.format(self.name)


### FLASK_SECURiTY ###

roles_users = db.Table('roles_users',
                     db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                     db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
                     )
### Пользователи ###
class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

class Role(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
    title = StringField('Заголовок')
    body = TextAreaField('Контент')

app.py
# -*- coding: utf-8 -*-
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_admin import AdminIndexView
from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_security import current_user
from flask import redirect, request, url_for

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

### Migrate ###
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


### Admin ###
from models import *

# Разграничение доступа к одминки и ее функциям
class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        # next='' <- Сыылка куда будет перенапровлятся пользователь
        return redirect( url_for('security.login', next=request.url))


class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generated_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)

class AdminView(AdminMixin, ModelView):
    pass


class HomeAdminView(AdminMixin, AdminIndexView):
    pass


class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body']

class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name']


admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))


### Flask-security ###
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
# -*- coding: utf-8 -*-
from app import app
from app import db
from posts.blueprint import posts

import view

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

posts/blueprint.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import render_template
from models import Post, Tag
from flask import request, redirect
from .forms import PostForm
from app import db
from flask import url_for
from flask_security import login_required
from flask import redirect, url_for, request


posts = Blueprint('posts', __name__, template_folder='templates')


''' Создание поста '''
# http://localhost/blog/create
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print ('Something wrong')

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


''' Редактирование поста '''
# http://localhost/blog/edit
@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


# http://localhost/blog/
@posts.route('/')
def index():
    # Поиск
    search = request.args.get('search')
    page = request.args.get('page')

    if page and page.isdigit(): # Если переменная имеет значение и переменная является цифрой
        page = int(page) # Преобразуем переменную в цифру
    else: # Иначе ...
        page = 1 # Даем значение переменной 1

    # если выполняется поиск
    if search:
        posts = Post.query.filter(Post.title.contains(search) | Post.body.contains(search))
    else: # иначе...
        #Выводим все посты
        posts = Post.query.order_by(Post.created.desc())

    # пагинация
    pages = posts.paginate(page=page, per_page=5)
    # Выводим шаблон
    return render_template('posts/index.html', posts=posts, pages=pages)


# http://localhost/blog/<slug>
@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


# http://localhost/blog/<slug>
@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title_page %}
    Создание поста
{% endblock %}

{% block content %}

<h1>Создание поста</h1>

<div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        {% for field in form %}
            <div class="form-group">
                {{ field.label() }}
                {{ field() }}
            </div>
        {% endfor %}
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Сохранить</button>
    </form>
</div>

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title_page %}
Редактирование поста
{% endblock %}

{% block content %}

<h1>Редактирование поста</h1>

<div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">

        {% for field in form %}
            <div class="form-group">
                {{ field.label() }}
                {{ field() }}
            </div>
        {% endfor %}

        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Создать</button>
    </form>
</div>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title_page %}
    Blueprint
{% endblock %}

{% block content %}
    <ul>
{% for post in pages.items %}
    <li><a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a></li>
{% endfor %}
    </ul>

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li
            {% if not pages.has_prev %}
                class="desabled"
            {% endif %}
            class="page-item">
            <a class="page-link" href="./?page={{ pages.prev_num }}">Previous</a>
        </li>

        {% for page in pages.iter_pages() %}
        <li class="
           {% if pages == pages.page %}
                active
           {% endif %}
           page-item">
           <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}

        <li {% if pages.has_next %}
                class="desabled"
            {% endif %}
            class="page-item">
            <a class="page-link" href="./?page={{ pages.next_num }}">Next</a>
        </li>
      </ul>
    </nav>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title_page %}
    {{ post.title}}
{% endblock %}

{% block content %}

<h1>{{ post.title}} </h1>
<p>{{ post.body}} </p>
<ul>
    {% for tag in tags %}

    <li><a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">{{ tag.name }}</li>

    {% endfor %}

</ul>

{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title_page %}
    Посты по тегам {{ tag.name }}
{% endblock %}

    {% block content %}

    <h1>Посты по тегам <strong>{{ tag.name }}</strong></h1>

    <ul>
    {% for post in posts %}

        <li><a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a></li>

    {% endfor %}
    </ul>

    {% endblock %}

templates/about.html
{% extends 'base.html' %}

{% block title_page %}
    about
{% endblock %}

{% block content %}
    ABOUT
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <title>{% block title_page %}{% endblock %} :: Flask</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Carousel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('about') }}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('contact') }}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('posts.index') }}">Posts</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/login">Вход</span></a>
            </li>
            {% if current_user.has_role('admin') %}
            <li class="nav-item">
                <a class="nav-link" href="/admin">Админка</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout">Выйти</span></a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline mt-2 mt-md-0" method="GET">
            <input class="form-control mr-sm-2" type="text" name="search" value="{{ request.args.get('search', '') }}" placeholder="Поиск" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">

            {% block content %}

            {% endblock %}

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">


        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </main><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

  </body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title_page %}
    content
{% endblock %}

{% block content %}
    CONTENT
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title_page %}
    Index
{% endblock %}

{% block content %}
    INDEX
{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}

    {% for category, message in messages %}
      <div class="alert alert-danger" role="alert">{{ message }}</div>
    {% endfor %}

  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block title_page %}
    {{ _('Login') }}
{% endblock %}

{% block content %}
    <div class="col-md-offset-3 col-md-6">
    {% from "security/_macros.html" import render_field_with_errors, render_field %}
    {% include "security/_messages.html" %}
    <h1>{{ _('Login') }}</h1>
    <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
      {{ login_user_form.hidden_tag() }}
      {{ render_field_with_errors(login_user_form.email, class='form-control') }}
      {{ render_field_with_errors(login_user_form.password, class='form-control') }}
      {{ render_field_with_errors(login_user_form.remember) }}
      {{ render_field(login_user_form.next) }}
      {{ render_field(login_user_form.submit) }}
    </form>
    {% include "security/_menu.html" %}
    </div>
{% endblock %}